#!/usr/bin/env python3
"""
Iterative prompt optimization loop.

Two-model design:
  OPTIMIZER_MODEL — judges responses, analyzes failures, rewrites prompts
  EXECUTOR_MODEL  — runs the prompt under test (isolated from the optimizer to avoid self-grading bias)

Test cases are provided by the trainer, not generated by the model.

Usage:
    python scripts/train.py "<intent>" "<initial_prompt>" <test_cases.json>

test_cases.json format:
    [
      {
        "input": "user message",
        "criteria": ["criterion 1", "criterion 2"]
      }
    ]
"""

import json
import os
import sys
from dataclasses import dataclass

import litellm
from dotenv import load_dotenv

from prepare import TestCase

load_dotenv()

OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")
OPENAI_BASE_URL = os.getenv("OPENAI_BASE_URL")

def _resolve_model(name: str) -> str:
    """When using a custom base URL, litellm requires an 'openai/' prefix to
    route the request through the OpenAI-compatible SDK. Add it automatically
    if the model name has no provider prefix."""
    if OPENAI_BASE_URL and "/" not in name:
        return f"openai/{name}"
    return name

OPTIMIZER_MODEL = _resolve_model(os.getenv("OPTIMIZER_MODEL", "gpt-4o"))
EXECUTOR_MODEL = _resolve_model(os.getenv("EXECUTOR_MODEL", "gpt-4o-mini"))

# Passed to every litellm.completion call
_api_kwargs: dict = {}
if OPENAI_API_KEY:
    _api_kwargs["api_key"] = OPENAI_API_KEY
if OPENAI_BASE_URL:
    _api_kwargs["api_base"] = OPENAI_BASE_URL

PASS_THRESHOLD = 0.8   # pass_rate >= this → early exit
MAX_ROUNDS = 5


# ---------------------------------------------------------------------------
# Data structures
# ---------------------------------------------------------------------------

@dataclass
class EvalResult:
    test_case: TestCase
    response: str
    passed: bool
    feedback: str         # which criteria passed / failed


@dataclass
class HistoryEntry:
    round: int
    prompt: str
    eval_results: list[EvalResult]
    pass_rate: float


# ---------------------------------------------------------------------------
# Step 1 — Execute (executor model, isolated)
# ---------------------------------------------------------------------------

def run_prompt(prompt: str, test_input: str) -> str:
    """Run the prompt under test against a single input using the executor model."""
    response = litellm.completion(
        model=EXECUTOR_MODEL,
        messages=[
            {"role": "system", "content": prompt},
            {"role": "user", "content": test_input},
        ],
        **_api_kwargs,
    )
    return response.choices[0].message.content


# ---------------------------------------------------------------------------
# Step 3 — Judge (optimizer model)
# ---------------------------------------------------------------------------

def judge(intent: str, test_case: TestCase, response: str) -> tuple[bool, str]:
    """Check the response against the test case's criteria. Returns (passed, feedback)."""
    criteria_list = "\n".join(f"- {c}" for c in test_case.criteria)
    result = litellm.completion(
        model=OPTIMIZER_MODEL,
        messages=[{
            "role": "user",
            "content": (
                f"Check whether this response satisfies all the given criteria.\n\n"
                f"<intent>{intent}</intent>\n"
                f"<input>{test_case.input}</input>\n"
                f"<response>{response}</response>\n\n"
                f"<criteria>\n{criteria_list}\n</criteria>\n\n"
                f"Reply in this exact format (two lines, nothing else):\n"
                f"RESULT: PASS  (or FAIL)\n"
                f"FEEDBACK: <one sentence listing which criteria passed or failed>"
            ),
        }],
        **_api_kwargs,
    )

    passed = False
    feedback = ""
    for line in result.choices[0].message.content.strip().splitlines():
        if line.startswith("RESULT:"):
            passed = "PASS" in line.upper()
        elif line.startswith("FEEDBACK:"):
            feedback = line.split(":", 1)[1].strip()

    return passed, feedback


# ---------------------------------------------------------------------------
# Evaluate one round
# ---------------------------------------------------------------------------

def evaluate(
    intent: str,
    prompt: str,
    test_cases: list[TestCase],
    round_num: int,
) -> HistoryEntry:
    eval_results: list[EvalResult] = []
    for tc in test_cases:
        response = run_prompt(prompt, tc.input)
        passed, feedback = judge(intent, tc, response)
        eval_results.append(EvalResult(test_case=tc, response=response, passed=passed, feedback=feedback))

    pass_rate = sum(1 for r in eval_results if r.passed) / len(eval_results)
    return HistoryEntry(round=round_num, prompt=prompt, eval_results=eval_results, pass_rate=pass_rate)


# ---------------------------------------------------------------------------
# Results logging
# ---------------------------------------------------------------------------

RESULTS_PATH = "results.jsonl"


def write_result(entry: HistoryEntry, gradient: str = "") -> None:
    """Append one round's result to results.jsonl."""
    record = {
        "round": entry.round,
        "pass_rate": round(entry.pass_rate, 4),
        "prompt": entry.prompt,
        "gradient": gradient,
        "failures": [
            {
                "input": r.test_case.input,
                "criteria": r.test_case.criteria,
                "feedback": r.feedback,
            }
            for r in entry.eval_results if not r.passed
        ],
    }
    with open(RESULTS_PATH, "a") as f:
        f.write(json.dumps(record, ensure_ascii=False) + "\n")


# ---------------------------------------------------------------------------
# Generate gradient and rewrite (optimizer model)
# ---------------------------------------------------------------------------

def generate_gradient(intent: str, prompt: str, entry: HistoryEntry, history: list[HistoryEntry]) -> str:
    failed = [r for r in entry.eval_results if not r.passed]
    failures_text = "\n".join(
        f"- Input: {r.test_case.input}\n"
        f"  Criteria: {', '.join(r.test_case.criteria)}\n"
        f"  Issue: {r.feedback}"
        for r in failed
    )

    # Build a summary of all previous rounds so the optimizer avoids repeating itself
    history_text = ""
    if len(history) > 1:
        lines = []
        for h in history[:-1]:   # all rounds except the current one
            try:
                prev_record = next(
                    json.loads(l) for l in open(RESULTS_PATH)
                    if json.loads(l).get("round") == h.round
                )
                prev_gradient = prev_record.get("gradient", "")
            except StopIteration:
                prev_gradient = ""
            lines.append(f"  Round {h.round}: pass_rate={h.pass_rate:.0%}  gradient applied: {prev_gradient[:120]}")
        history_text = "\n<history>\n" + "\n".join(lines) + "\n</history>\n"

    response = litellm.completion(
        model=OPTIMIZER_MODEL,
        messages=[{
            "role": "user",
            "content": (
                f"A prompt is failing to satisfy evaluation criteria on some test cases.\n"
                f"Read the history of previous rounds to avoid repeating the same fixes.\n\n"
                f"<intent>{intent}</intent>\n"
                f"{history_text}\n"
                f"<current_prompt>\n{prompt}\n</current_prompt>\n\n"
                f"<failures>\n{failures_text}\n</failures>\n\n"
                f"Identify the root causes. What is the prompt missing, ambiguous about, or doing wrong?\n"
                f"Be specific and actionable. Output 3–5 bullet points."
            ),
        }],
        **_api_kwargs,
    )
    return response.choices[0].message.content.strip()


def rewrite_prompt(intent: str, prompt: str, gradient: str) -> str:
    response = litellm.completion(
        model=OPTIMIZER_MODEL,
        messages=[{
            "role": "user",
            "content": (
                f"Rewrite this prompt to fix the identified issues while preserving what works.\n\n"
                f"<intent>{intent}</intent>\n\n"
                f"<current_prompt>\n{prompt}\n</current_prompt>\n\n"
                f"<issues_to_fix>\n{gradient}\n</issues_to_fix>\n\n"
                f"Output ONLY the improved prompt text. No preamble, no explanation."
            ),
        }],
        **_api_kwargs,
    )
    return response.choices[0].message.content.strip()


# ---------------------------------------------------------------------------
# Main optimization loop
# ---------------------------------------------------------------------------

def optimize(
    intent: str,
    prompt: str,
    test_cases: list[TestCase],
) -> tuple[str, float, list[HistoryEntry]]:
    history: list[HistoryEntry] = []
    current_prompt = prompt

    # Clear results file for this run
    open(RESULTS_PATH, "w").close()

    for round_num in range(1, MAX_ROUNDS + 1):
        print(f"\n--- Round {round_num}/{MAX_ROUNDS} ---")

        entry = evaluate(intent, current_prompt, test_cases, round_num)
        history.append(entry)

        print(f"  pass_rate={entry.pass_rate:.0%}")
        for r in entry.eval_results:
            status = "PASS" if r.passed else "FAIL"
            print(f"  [{status}] {r.test_case.input[:60]}... — {r.feedback}")

        # Early exit: threshold met
        if entry.pass_rate >= PASS_THRESHOLD:
            write_result(entry)
            print(f"  Pass rate {entry.pass_rate:.0%} >= threshold. Stopping.")
            break

        # Last round: skip rewrite to avoid a wasted API call
        if round_num == MAX_ROUNDS:
            write_result(entry)
            print("  Max rounds reached.")
            break

        gradient = generate_gradient(intent, current_prompt, entry, history)
        print(f"\n  Gradient:\n    " + gradient.replace("\n", "\n    "))

        write_result(entry, gradient)

        current_prompt = rewrite_prompt(intent, current_prompt, gradient)
        print(f"\n  New prompt:\n    " + current_prompt[:200].replace("\n", "\n    "))

    best = max(history, key=lambda e: e.pass_rate)
    return best.prompt, best.pass_rate, history


# ---------------------------------------------------------------------------
# CLI entry point
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    if len(sys.argv) < 4:
        print("Usage: python scripts/train.py \"<intent>\" <prompt.txt> <test_cases.jsonl>")
        sys.exit(1)

    intent = sys.argv[1]
    prompt_path = sys.argv[2]
    test_cases_path = sys.argv[3]

    with open(prompt_path) as f:
        initial_prompt = f.read().strip()

    print(f"Intent           : {intent}")
    print(f"Prompt file      : {prompt_path}")
    print(f"Optimizer model  : {OPTIMIZER_MODEL}")
    print(f"Executor model   : {EXECUTOR_MODEL}")

    print(f"\nLoading test cases from {test_cases_path}...")
    with open(test_cases_path) as f:
        test_cases = [TestCase(input=r["input"], criteria=r["criteria"]) for r in (json.loads(l) for l in f if l.strip())]
    for i, tc in enumerate(test_cases, 1):
        print(f"  {i}. {tc.input}")
        for c in tc.criteria:
            print(f"       - {c}")

    best_prompt, best_pass_rate, history = optimize(intent, initial_prompt, test_cases)

    print(f"\n{'=' * 60}")
    print(f"Best pass rate : {best_pass_rate:.0%}")
    print(f"Best prompt    :\n{best_prompt}")
    print(f"\nRound summary:")
    for e in history:
        print(f"  Round {e.round}: pass_rate={e.pass_rate:.0%}")

    # Update prompt.txt if the best prompt is different from the initial one
    if best_prompt != initial_prompt:
        with open(prompt_path, "w") as f:
            f.write(best_prompt)
        print(f"\nUpdated {prompt_path} with the best prompt.")
